/* =====================================================================
   Ready-made careers: eras, stages and guitar-friendly song picks written
   in advance, so they build without Claude (and without an API key). They
   still go through the same checks as any career: albums and years come
   from MusicBrainz / Apple, every song has to be on its album and pass
   the chord check, and the era rules decide the names.
   Albums are named by title; songs by title and album title.
   ===================================================================== */
const CURATED = [
  { artist: 'Oasis', tagline: 'From a Manchester rehearsal room to Knebworth and back', levels: [
    { albums: ['Definitely Maybe'], name: 'Definitely Maybe', period: 'Burnage Beginnings', blurb: 'Loud guitars and big hooks from a Manchester rehearsal room, the fastest-selling debut in Britain at the time.',
      scene: { stage: 'A cramped Manchester rehearsal room at night, amps stacked against brick', setting: 'garage', time: 'night', palette: ['#3C4A6B', '#E8B04A', '#E04E3C'], props: ['amps', 'speakers', 'string-lights'], motif: 'star', sign: 'BOARDWALK', posters: ['MANCHESTER 94', 'SOLD OUT'] },
      songs: [['Live Forever', 'Definitely Maybe', 'Big open-chord anthem', 89, 1], ['Supersonic', 'Definitely Maybe', 'Slow grinding riff, few chords', 105, 1], ['Cigarettes & Alcohol', 'Definitely Maybe', 'Glam boogie on two chords', 104, 1], ['Slide Away', 'Definitely Maybe', 'Sweeping chord changes', 100, 1], ['Shakermaker', 'Definitely Maybe', 'Lazy four-chord loop', 94, 1]] },
    { albums: ["(What's the Story) Morning Glory?"], name: "(What's the Story) Morning Glory?", period: 'Britpop Summit', blurb: 'The album that made them the biggest band in Britain: stadium singalongs and a record-breaking run of gigs.',
      scene: { stage: 'A packed open-air field at dusk, flags and floodlights over the crowd', setting: 'festival', time: 'dusk', palette: ['#2B3A67', '#F2A541', '#F25C54'], props: ['speakers', 'string-lights', 'balloons'], motif: 'sun', sign: 'KNEBWORTH', posters: ['1996', 'MAINE ROAD'] },
      songs: [['Wonderwall', "(What's the Story) Morning Glory?", 'The famous capo strum everyone learns', 87, 1], ["Don't Look Back in Anger", "(What's the Story) Morning Glory?", 'Piano-led chords that ring on guitar', 83, 1], ['Champagne Supernova', "(What's the Story) Morning Glory?", 'Slow, dreamy four-chord build', 76, 1], ['Some Might Say', "(What's the Story) Morning Glory?", 'Driving open-chord rock', 110, 1], ['Morning Glory', "(What's the Story) Morning Glory?", 'Chugging riff with a big chorus', 116, 1], ['Cast No Shadow', "(What's the Story) Morning Glory?", 'Gentle acoustic strum', 82, 1]] },
    { albums: ['Be Here Now', 'Standing on the Shoulder of Giants', 'Heathen Chemistry', "Don't Believe the Truth", 'Dig Out Your Soul'], name: 'Stadium Swagger', period: 'Stadium Swagger', blurb: 'Bigger, longer, louder: the arena years, then a leaner band finding its feet again.',
      scene: { stage: 'An arena at night under a lighting rig, pyro jets ready at the stage edge', setting: 'arena', time: 'night', palette: ['#171A33', '#F2C14E', '#4FC3F7'], props: ['lasers', 'pyro', 'speakers'], motif: 'bolt', sign: 'SOLD OUT', posters: ['WORLD TOUR', '2005'] },
      songs: [['Stop Crying Your Heart Out', 'Heathen Chemistry', 'Slow piano-ballad chords', 70, 1], ['Stand by Me', 'Be Here Now', 'Big singalong chords', 80, 1], ['Songbird', 'Heathen Chemistry', 'Short, sweet two-minute strum', 118, 1], ['Little by Little', 'Heathen Chemistry', 'Open chords with a big chorus', 84, 1], ["Don't Go Away", 'Be Here Now', 'Slow power ballad', 72, 1], ['Lyla', "Don't Believe the Truth", 'Stomping four-chord rocker', 124, 1], ['The Importance of Being Idle', "Don't Believe the Truth", 'Swinging minor-key strum', 122, 2]] },
  ] },
  { artist: 'Taylor Swift', tagline: 'From Nashville writing rooms to the biggest tour on earth', levels: [
    { albums: ['Taylor Swift', 'Fearless'], name: 'Nashville Beginnings', period: 'Nashville Beginnings', blurb: 'A teenage songwriter on Music Row, guitar in hand, playing radio stations and county fairs.',
      scene: { stage: 'A small-town fairground at dusk, hay bales and string lights round the stage', setting: 'countryside', time: 'dusk', palette: ['#6B8F4E', '#F2C94C', '#F28DB2'], props: ['hay-bales', 'string-lights', 'flowers'], motif: 'heart', sign: 'COUNTY FAIR', posters: ['NASHVILLE 2006', 'OPEN MIC'] },
      songs: [['Our Song', 'Taylor Swift', 'Bouncy four-chord country strum', 89, 1], ['Teardrops on My Guitar', 'Taylor Swift', 'Gentle capo strum', 100, 1], ['Tim McGraw', 'Taylor Swift', 'Slow open-chord ballad', 76, 1], ['Love Story', 'Fearless', 'The capo strum everyone knows', 119, 1], ['You Belong with Me', 'Fearless', 'Driving four-chord pop-country', 130, 1], ['White Horse', 'Fearless', 'Soft piano chords on guitar', 92, 1], ['Fifteen', 'Fearless', 'Fingerpicked-friendly chords', 96, 1]] },
    { albums: ['Speak Now', 'Red', '1989'], name: 'The Pop Crossover', period: 'The Pop Crossover', blurb: 'From writing every song alone to the biggest pop album of its year, and her first stadium tours.',
      scene: { stage: 'A stadium stage at night with a runway into the crowd and confetti cannons', setting: 'arena', time: 'night', palette: ['#241B45', '#F24E6E', '#6FD6FF'], props: ['lasers', 'speakers', 'string-lights'], motif: 'star', sign: 'NEW YORK', posters: ['WORLD TOUR', '2014'] },
      songs: [['Mine', 'Speak Now', 'Bright four-chord strum', 121, 1], ['Mean', 'Speak Now', 'Banjo-style open chords', 82, 1], ['Back to December', 'Speak Now', 'Slow strummed ballad', 71, 1], ['We Are Never Ever Getting Back Together', 'Red', 'Simple chugging chords', 86, 1], ['Red', 'Red', 'Driving capo strum', 125, 1], ['All Too Well', 'Red', 'Four chords, long and slow', 93, 1], ['Shake It Off', '1989', 'Three-chord pop groove', 160, 1], ['Blank Space', '1989', 'Easy repeating progression', 96, 1], ['Style', '1989', 'Funky muted-chord groove', 95, 1]] },
    { albums: ['reputation', 'Lover', 'folklore', 'evermore'], name: 'Woodland Reinvention', period: 'Woodland Reinvention', blurb: 'Snakes, pastels, then a quiet turn to cabins and forests, writing stories far from the spotlight.',
      scene: { stage: 'A misty forest clearing at dusk with a campfire and a wooden piano', setting: 'mountains', time: 'dusk', palette: ['#4A5A52', '#E9D9B6', '#9FB7A6'], props: ['campfire', 'piano', 'plants'], motif: 'moon', sign: 'THE CABIN', posters: ['FOLKLORE', '2020'] },
      songs: [['Delicate', 'reputation', 'Soft four-chord loop', 95, 1], ['Lover', 'Lover', 'Slow waltz-time strum', 68, 1], ['cardigan', 'folklore', 'Piano chords that sit well on guitar', 130, 1], ['exile', 'folklore', 'Slow piano ballad chords', 76, 1], ['betty', 'folklore', 'Harmonica-era folk strum', 96, 1], ['willow', 'evermore', 'Fingerpicked minor loop', 81, 1], ['champagne problems', 'evermore', 'Piano ballad, gentle changes', 85, 1], ['Cruel Summer', 'Lover', 'Synth-pop chords, easy loop', 170, 1]] },
  ] },
  { artist: 'The Beatles', tagline: 'From Liverpool clubs to the studio that changed pop music', levels: [
    { albums: ['Please Please Me', 'With the Beatles', "A Hard Day's Night", 'Beatles for Sale', 'Help!'], name: 'Beatlemania', period: 'Beatlemania', blurb: 'Leather jackets, Liverpool cellars and screaming crowds: two-minute songs built on bright open chords.',
      scene: { stage: 'A brick cellar club in Liverpool, arched ceiling and a tiny stage', setting: 'club', time: 'night', palette: ['#5A3A2E', '#F2C14E', '#E85D4A'], props: ['amps', 'string-lights', 'speakers'], motif: 'note', sign: 'THE CELLAR', posters: ['LIVERPOOL 63', 'HAMBURG'] },
      songs: [['Love Me Do', 'Please Please Me', 'Three open chords', 148, 1], ['Twist and Shout', 'Please Please Me', 'The classic three-chord shout', 124, 1], ['I Saw Her Standing There', 'Please Please Me', 'Rocking open-chord boogie', 160, 1], ['All My Loving', 'With the Beatles', 'Fast strummed triplets', 155, 2], ["A Hard Day's Night", "A Hard Day's Night", 'That famous opening chord', 138, 1], ['And I Love Her', "A Hard Day's Night", 'Gentle acoustic ballad', 110, 1], ['Eight Days a Week', 'Beatles for Sale', 'Bouncy major chords', 138, 1], ['Help!', 'Help!', 'Driving strum, easy shapes', 190, 1], ['Yesterday', 'Help!', 'Acoustic ballad classic', 97, 2], ['Ticket to Ride', 'Help!', 'Jangling guitar riff', 124, 1]] },
    { albums: ['Rubber Soul', 'Revolver', "Sgt. Pepper's Lonely Hearts Club Band"], name: 'The Studio Years', period: 'The Studio Years', blurb: 'No more touring: the band moves into the studio and turns records into art.',
      scene: { stage: 'A London recording studio at night, tape machines and a grand piano', setting: 'studio', time: 'night', palette: ['#2E3550', '#F4D35E', '#EE964B'], props: ['piano', 'speakers', 'plants'], motif: 'eye', sign: 'STUDIO TWO', posters: ['LONDON 1966', 'ON AIR'] },
      songs: [['Norwegian Wood (This Bird Has Flown)', 'Rubber Soul', 'Waltz-time acoustic strum', 180, 1], ['In My Life', 'Rubber Soul', 'Warm fingerpicked chords', 103, 1], ['Nowhere Man', 'Rubber Soul', 'Big three-part-harmony chords', 124, 1], ['Michelle', 'Rubber Soul', 'Jazzy chord shapes', 124, 2], ['Here, There and Everywhere', 'Revolver', 'Soft ballad changes', 82, 2], ['Yellow Submarine', 'Revolver', 'Easy singalong chords', 111, 1], ['With a Little Help from My Friends', "Sgt. Pepper's Lonely Hearts Club Band", 'Friendly open-chord groove', 110, 1], ['Lucy in the Sky with Diamonds', "Sgt. Pepper's Lonely Hearts Club Band", 'Dreamy waltz chords', 130, 1]] },
    { albums: ['The Beatles', 'Abbey Road', 'Let It Be'], name: 'The Final Chapter', period: 'The Final Chapter', blurb: 'Four songwriters pulling in different directions, and some of the best songs they ever wrote.',
      scene: { stage: 'A London rooftop at dusk, amps in the wind over the city', setting: 'rooftop', time: 'dusk', palette: ['#3A4E6B', '#F2B880', '#E86A5A'], props: ['amps', 'speakers', 'plants'], motif: 'sun', sign: 'SAVILE ROW', posters: ['1969', 'LONDON'] },
      songs: [['Let It Be', 'Let It Be', 'Four-chord piano classic on guitar', 72, 1], ['Here Comes the Sun', 'Abbey Road', 'Bright capo-7 acoustic', 129, 1], ['Blackbird', 'The Beatles', 'Fingerpicked acoustic showpiece', 94, 2], ['Something', 'Abbey Road', 'Lush chord changes', 66, 2], ['Come Together', 'Abbey Road', 'Swampy groove, few chords', 82, 1], ['Two of Us', 'Let It Be', 'Strummed acoustic duet', 110, 1], ['Across the Universe', 'Let It Be', 'Slow acoustic chords', 78, 1], ['Dear Prudence', 'The Beatles', 'Fingerpicked descending line', 116, 1], ['While My Guitar Gently Weeps', 'The Beatles', 'Minor-key chord walk-down', 116, 2]] },
  ] },
  { artist: 'Nirvana', tagline: 'From an Aberdeen garage to the sound of a generation', levels: [
    { albums: ['Bleach'], name: 'Bleach', period: 'Aberdeen Garage', blurb: 'Recorded for a few hundred dollars in Seattle: heavy, slow and raw, played in basements and small clubs.',
      scene: { stage: 'A rainy Pacific Northwest garage, amps and a leaky roof', setting: 'garage', time: 'night', palette: ['#3E4A4F', '#C9B458', '#C4453B'], props: ['amps', 'speakers', 'plants'], motif: 'flame', sign: 'SEATTLE', posters: ['ALL AGES', '1989'] },
      songs: [['About a Girl', 'Bleach', 'Jangly two-chord verse, easy chorus', 132, 1], ['School', 'Bleach', 'One heavy riff, a few chords', 122, 1], ['Negative Creep', 'Bleach', 'Fast, heavy power chords', 148, 1], ['Love Buzz', 'Bleach', 'Hypnotic riff over few chords', 132, 1]] },
    { albums: ['Nevermind'], name: 'Nevermind', period: 'Grunge Explosion', blurb: 'One album knocked the biggest pop star off the top of the charts and turned Seattle into the centre of rock.',
      scene: { stage: 'A packed club at night, a high school gym feel with smoke and spotlights', setting: 'club', time: 'night', palette: ['#1F3A5F', '#F2E863', '#F24C4C'], props: ['amps', 'speakers', 'pennants'], motif: 'bolt', sign: 'PEP RALLY', posters: ['1991', 'TONIGHT'] },
      songs: [['Smells Like Teen Spirit', 'Nevermind', 'The four power chords everyone knows', 117, 1], ['Come as You Are', 'Nevermind', 'Famous murky riff', 120, 1], ['Lithium', 'Nevermind', 'Quiet verse, loud chorus chords', 123, 2], ['In Bloom', 'Nevermind', 'Heavy riff, catchy chords', 156, 1], ['Polly', 'Nevermind', 'Quiet acoustic strum', 121, 1], ['Something in the Way', 'Nevermind', 'Two slow acoustic chords', 106, 1]] },
    { albums: ['In Utero'], name: 'In Utero', period: 'The Last Record', blurb: 'A rawer, darker album recorded fast in a snowy Minnesota studio.',
      scene: { stage: 'A snowbound studio cabin at night, amps and candles', setting: 'mountains', time: 'night', weather: 'snow', palette: ['#2B3242', '#E8D8A8', '#D9534F'], props: ['amps', 'candles', 'speakers'], motif: 'heart', sign: 'MINNESOTA', posters: ['1993', 'SOLD OUT'] },
      songs: [['Heart-Shaped Box', 'In Utero', 'Brooding three-chord verse', 101, 1], ['All Apologies', 'In Utero', 'Drone-y strum, easy shapes', 112, 1], ['Dumb', 'In Utero', 'Gentle chords, cello-friendly', 108, 1], ['Pennyroyal Tea', 'In Utero', 'Quiet verse, big chorus', 138, 1]] },
  ] },
  { artist: 'Green Day', tagline: 'From East Bay punk clubs to a rock opera on Broadway', levels: [
    { albums: ['Dookie'], name: 'Dookie', period: 'East Bay Punks', blurb: 'Three kids from the East Bay punk scene hit the big time with fast, funny, three-chord songs.',
      scene: { stage: 'A graffiti-covered punk club in the East Bay, a low stage and a mosh pit', setting: 'street', time: 'night', palette: ['#3D2C5E', '#9BE564', '#F2545B'], props: ['amps', 'boombox', 'speakers'], motif: 'bolt', sign: '924 GILMAN', posters: ['ALL AGES', '1994'] },
      songs: [['Basket Case', 'Dookie', 'Fast power-chord punk', 170, 1], ['When I Come Around', 'Dookie', 'Four chords on repeat', 98, 1], ['Longview', 'Dookie', 'Bass-led verse, loud chorus', 144, 1], ['Welcome to Paradise', 'Dookie', 'Punk chords, easy shapes', 176, 1], ['She', 'Dookie', 'Short, driving power chords', 136, 1]] },
    { albums: ['Insomniac', 'Nimrod', 'Warning'], name: 'After the Breakthrough', period: 'After the Breakthrough', blurb: 'Faster, angrier, then acoustic and folky: the band stretches out beyond three chords.',
      scene: { stage: 'A sweaty theatre at night, strobes and a banner over the stage', setting: 'theater', time: 'night', palette: ['#2F2440', '#F2A541', '#6BCB77'], props: ['amps', 'speakers', 'string-lights'], motif: 'eye', sign: 'TONIGHT', posters: ['NIMROD TOUR', '1998'] },
      songs: [['Good Riddance (Time of Your Life)', 'Nimrod', 'The famous acoustic strum', 95, 1], ['Brain Stew', 'Insomniac', 'One slow power-chord riff', 128, 1], ['Hitchin\' a Ride', 'Nimrod', 'Moody chords with a stomp', 124, 1], ['Minority', 'Warning', 'Bright acoustic punk', 150, 1], ['Warning', 'Warning', 'Bouncy open chords', 134, 1], ['Walking Contradiction', 'Insomniac', 'Quick punk changes', 176, 1]] },
    { albums: ['American Idiot'], name: 'American Idiot', period: 'Rock Opera', blurb: 'A concept album about growing up in a divided country, played in stadiums and later on Broadway.',
      scene: { stage: 'A stadium at night in red and black, pyro and a giant grenade backdrop', setting: 'arena', time: 'night', palette: ['#1A1A1A', '#E63946', '#F1FAEE'], props: ['pyro', 'lasers', 'speakers'], motif: 'heart', sign: 'JESUS OF SUBURBIA', posters: ['2004', 'SOLD OUT'] },
      songs: [['Boulevard of Broken Dreams', 'American Idiot', 'Four moody chords on repeat', 83, 1], ['Wake Me Up When September Ends', 'American Idiot', 'Fingerpicked ballad chords', 105, 1], ['American Idiot', 'American Idiot', 'Big punk power chords', 186, 1], ['Holiday', 'American Idiot', 'Stomping minor-key chords', 146, 1], ['Give Me Novacaine', 'American Idiot', 'Soft acoustic changes', 136, 1]] },
  ] },
  { artist: 'Coldplay', tagline: 'From a London student flat to the biggest stadium shows in the world', levels: [
    { albums: ['Parachutes'], name: 'Parachutes', period: 'Student Days', blurb: 'Four university friends in London make a quiet, acoustic debut that turns into a worldwide hit.',
      scene: { stage: 'A small London student flat at night, fairy lights and a piano against the wall', setting: 'studio', time: 'night', palette: ['#23355B', '#F2D16B', '#89C2D9'], props: ['piano', 'string-lights', 'plants'], motif: 'star', sign: 'CAMDEN', posters: ['2000', 'OPEN MIC'] },
      songs: [['Yellow', 'Parachutes', 'The big open-chord strum', 87, 1], ['Trouble', 'Parachutes', 'Piano ballad chords', 70, 1], ['Shiver', 'Parachutes', 'Swaying 6/8 chords', 118, 1], ["Don't Panic", 'Parachutes', 'Short acoustic strum', 128, 1], ['Sparks', 'Parachutes', 'Quiet, slow changes', 68, 1]] },
    { albums: ['A Rush of Blood to the Head'], name: 'A Rush of Blood to the Head', period: 'The Breakthrough', blurb: 'Bigger songs, bigger halls: the piano moves to the front and the band starts filling arenas.',
      scene: { stage: 'A concert hall at night with a grand piano centre stage and warm lights', setting: 'theater', time: 'night', palette: ['#3B1F2B', '#F2C14E', '#E63946'], props: ['piano', 'speakers', 'chandelier'], motif: 'diamond', sign: 'TONIGHT', posters: ['2002', 'WORLD TOUR'] },
      songs: [['The Scientist', 'A Rush of Blood to the Head', 'Four piano chords, easy on guitar', 75, 1], ['Clocks', 'A Rush of Blood to the Head', 'Famous piano loop on three chords', 131, 1], ['In My Place', 'A Rush of Blood to the Head', 'Slow, big open chords', 72, 1], ['Warning Sign', 'A Rush of Blood to the Head', 'Gentle strummed chords', 112, 1], ['God Put a Smile upon Your Face', 'A Rush of Blood to the Head', 'Driving acoustic riff', 128, 1]] },
    { albums: ['X&Y', 'Viva la Vida or Death and All His Friends'], name: 'Stadium Years', period: 'Stadium Years', blurb: 'Stadium anthems, painted jackets and a crowd of lights: the band becomes one of the biggest in the world.',
      scene: { stage: 'A stadium at night under confetti and a sky of wristband lights', setting: 'arena', time: 'night', weather: 'confetti', palette: ['#1B1F3B', '#F5B700', '#F72585'], props: ['lasers', 'balloons', 'speakers'], motif: 'crown', sign: 'SOLD OUT', posters: ['VIVA TOUR', '2008'] },
      songs: [['Fix You', 'X&Y', 'Organ-style chords, slow build', 69, 1], ['Viva la Vida', 'Viva la Vida or Death and All His Friends', 'Four famous string chords', 138, 1], ['Speed of Sound', 'X&Y', 'Driving piano chords', 123, 1], ['Talk', 'X&Y', 'Chugging riff, easy chords', 128, 1], ['Violet Hill', 'Viva la Vida or Death and All His Friends', 'Stomping minor chords', 76, 1], ['Lovers in Japan', 'Viva la Vida or Death and All His Friends', 'Bright piano chords', 125, 1]] },
  ] },
  { artist: 'Kanye West', tagline: 'From a Chicago bedroom studio to stadium anthems', levels: [
    { albums: ['The College Dropout'], name: 'The College Dropout', period: 'Chicago Come-Up', blurb: 'A Chicago producer steps out from behind the boards with sped-up soul samples and a backpack full of rhymes.',
      scene: { stage: 'A South Side dorm-room studio at night, CD stacks by the window', setting: 'campus', time: 'night', palette: ['#3B2F63', '#FFB020', '#FF5E7E'], props: ['cd-table', 'boombox', 'books', 'turntables'], motif: 'crown', sign: 'SOUTH SIDE', posters: ['CHICAGO 2003', 'OPEN MIC'] },
      songs: [['All Falls Down', 'The College Dropout', 'Famous acoustic guitar loop', 91, 1], ['Through the Wire', 'The College Dropout', 'Sped-up soul loop', 83, 1], ['Slow Jamz', 'The College Dropout', 'Smooth soul chords', 72, 2], ['Spaceship', 'The College Dropout', 'Soul sample loop', 80, 1], ['Never Let Me Down', 'The College Dropout', 'Minor chord loop', 80, 1]] },
    { albums: ['Late Registration', 'Graduation'], name: 'Stadium Years', period: 'Stadium Years', blurb: 'Strings, horns and synths: the arena tours begin and the sound gets bigger with every record.',
      scene: { stage: 'An arena stage with a giant LED sky and lasers', setting: 'arena', time: 'night', palette: ['#1A1633', '#FF4FA0', '#4FE3FF'], props: ['lasers', 'pyro', 'speakers'], motif: 'bolt', sign: 'SOLD OUT', posters: ['GLOW TOUR', '2007'] },
      songs: [["Heard 'Em Say", 'Late Registration', 'Piano ballad chords', 90, 1], ['Touch the Sky', 'Late Registration', 'Horn loop over bright chords', 100, 1], ['Hey Mama', 'Late Registration', 'Warm soul chords', 86, 1], ['Homecoming', 'Graduation', 'Bouncy piano hook', 87, 1], ['Flashing Lights', 'Graduation', 'String chords, easy loop', 90, 1], ['Everything I Am', 'Graduation', 'Soft piano loop', 80, 1], ['Good Life', 'Graduation', 'Four sunny chords', 84, 1]] },
    { albums: ['808s & Heartbreak', 'My Beautiful Dark Twisted Fantasy'], name: 'Heartbreak & Excess', period: 'Heartbreak & Excess', blurb: 'Grief and fame pour into cold synths, then into a lavish, maximal masterpiece.',
      scene: { stage: 'A stark white art space at night with a giant red light and a grand piano', setting: 'artspace', time: 'night', palette: ['#2B2B2B', '#E63946', '#F1FAEE'], props: ['piano', 'sculpture', 'candles'], motif: 'heart', sign: 'HAWAII', posters: ['2010', 'FANTASY'] },
      songs: [['Street Lights', '808s & Heartbreak', 'Four-chord loop', 85, 1], ['Coldest Winter', '808s & Heartbreak', 'Minor piano chords', 80, 1], ['Heartless', '808s & Heartbreak', 'Pulsing four chords', 88, 1], ['Love Lockdown', '808s & Heartbreak', 'Two moody chords', 120, 1], ['Runaway', 'My Beautiful Dark Twisted Fantasy', 'Famous piano hook', 85, 1], ['Lost in the World', 'My Beautiful Dark Twisted Fantasy', 'Big chords, slow build', 104, 1]] },
  ] },
];
